### PR TITLE
Update Footer.jsx

### LINKED ISSUE #34: Copyright bug
Currently the copyright year is a direct copy paste , It should be dynamic in nature using javascript to get current year , @Muskansahuincredible @techmannih  assign this issue to me I will fix it , I am working under gssoc

### PR DESCRIPTION
**Pull request by Meetjain1**
## Related Issue
closes #34 

## Description
Updated copyright year code to make it dynamic in nature , now it will capture current year rather than earlier pasted plain text year.

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
study4

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by techmannih — APPROVED** [review]
approval

**Comment by Meetjain1** [comment]
@techmannih please label gssoc and level label in this PR.

**Comment by Meetjain1** [comment]
@techmannih please assign me also in this PR. Otherwise gssoc will not count it.

**Comment by Meetjain1** [comment]
> @techmannih please assign me also in this PR. Otherwise gssoc will not count it.

@Muskansahuincredible @techmannih

**Pull request merged**
