### PR TITLE
Update README.md

### LINKED ISSUE #32: Readme.md Update Required
Currently Our readme.md file is not looking good 
It is looking like a learn.md file I would suggest to @Muskansahuincredible @techmannih  assign me this issue I will create a fully new version of readme file , have created the same in many repository , I am working under gssoc

changes required are missing video of our project , allignment of text , open source section , contributors section , code of conduct, license section , features section and many more I will create a beautiful attracting readme file .

### PR DESCRIPTION
**Pull request by Meetjain1**
## Related Issue
closes #32 

## Description
Updated readme.md to a fully new version

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by techmannih — APPROVED** [review]
approval

**Comment by Meetjain1** [comment]
@techmannih please label gssoc and Level labels in this pr.

**Comment by Meetjain1** [comment]
@techmannih please assign me also in this PR.

**Comment by Meetjain1** [comment]
> @techmannih please assign me also in this PR.

@techmannih @Muskansahuincredible .
otherwise gssoc not count it .

**Pull request merged**
