### PR TITLE
Added Smooth Scroll-Activated 'Back to Top' Button for Enhanced User Experience

### PR DESCRIPTION
**Pull request by AsmitaMishra24**
## Related Issue
#136 

## Description
Added a smooth scroll-activated 'Back to Top' button to enhance user experience on the website. The button is triggered when users scroll down the page, providing a convenient way to navigate back to the top without manually scrolling.

- Changes Made:
1. Implemented a 'Back to Top' button with smooth scroll activation.
2. Added transition effects for a seamless user experience.
3. Integrated JavaScript functionality to detect scroll position and display the button accordingly.
4. Ensured compatibility across different browsers for consistent behavior.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/146121869/e20c94c1-f7c5-4a32-a9d2-4be9821e468a

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
.

### CODE REVIEW

**Comment by AsmitaMishra24** [comment]
@techmannih, please review the PR

**Comment by AsmitaMishra24** [comment]
@techmannih, I have resolved the merge conflicts. 
Before merging, please assign the #136 issue to me, as the previously assigned person informed that he could not complete the task due to a technical issue. Also, if you find my work meets your expectations, please upgrade my level to level 2.

**Comment by AsmitaMishra24** [comment]
> @techmannih, I have resolved the merge conflicts. Before merging, please assign the #136 issue to me, as the previously assigned person informed that he could not complete the task due to a technical issue. Also, if you find my work meets your expectations, please upgrade my level to level 2.

The merge, conflicts were present in two files: ReviewSlider.jsx and CourseSlider.jsx. When I ran the code on my computer, errors appeared in these two files. I made changes based on the documentation, and then the code started working.

**Comment by AsmitaMishra24** [comment]
@Muskansahuincredible, please assign the #136 issue and also assign this PR and add labels.
Also, if you find my work meets your expectations, please upgrade my level to level 2.

**Comment by AsmitaMishra24** [comment]
> @Muskansahuincredible, please assign the #136 issue and also assign this PR and add labels. Also, if you find my work meets your expectations, please upgrade my level to level 2.

@techmannih

**Comment by AsmitaMishra24** [comment]
> @Muskansahuincredible, please assign the #136 issue and also assign this PR and add labels. Also, if you find my work meets your expectations, please upgrade my level to level 2.

@Muskansahuincredible, please assign the issue and PR

**Comment by sanjay-kv** [comment]
@Muskansahuincredible 
the labels has not been done yet. could you add me into the repo so i can manage the label related issues?
sent an official mail

**Pull request merged**
