### PR TITLE
Added project section 

### LINKED ISSUE #188: 💡[FEATURE] Project Section
### Description

I want to add a project section so that if someone wants to learn any language or concept, they can learn it by working on a project continuously.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

### PR DESCRIPTION
**Pull request by Vijayaa21**
## Related Issue
fixes #188 and #189 

## Description
I have added a new page where users can enhance their learning experience by creating projects and immersing themselves in the language. This hands-on approach allows for a more practical and interactive learning environment, providing users with an opportunity to apply their knowledge in real-world scenarios.

## Type of PR

- [ ] Bug fix
- [✅] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

Screenshot 2024-06-28 131914

## Checklist:
- [✅ ] I have performed a self-review of my code
- [✅ ] I have read and followed the Contribution Guidelines.
- [✅ ] I have tested the changes thoroughly before submitting this pull request.
- [✅ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Also added improved the learning grid section 
Screenshot 2024-06-15 091542

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
@Vijayaa21 Please resolve the conflicts in your PR.

**Comment by Vijayaa21** [comment]
conflict resolved

**Comment by Agarwalvidu** [comment]
This PR is approved by my side @Muskansahuincredible please review it once on and merge it.

**Comment by Agarwalvidu** [comment]
@Vijayaa21 
Can you please share more relevant videos to your work?

**Comment by Agarwalvidu** [comment]
@Vijayaa21 Are you active?

**Comment by Vijayaa21** [comment]
> @Vijayaa21 Are you active?
yes, I am attaching video 

https://github.com/user-attachments/assets/4c8a2aab-19ef-4b2e-a744-d33d38a5f1e3

**Pull request merged**
