### PR TITLE
Added pull_request_template.md

### LINKED ISSUE #23: Want to add a PR template for this repo
Please assign me under GSSOC'24

### PR DESCRIPTION
**Pull request by suhanipaliwal**
Fixes #23

### CODE REVIEW

**Review by techmannih — APPROVED** [review]
approval

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this pr.

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this pr.

**Comment by suhanipaliwal** [comment]
Please add the label of level1

**Pull request merged**
