### PR TITLE
fixed the dropdown issue

### PR DESCRIPTION
**Pull request by Utsavladia**
## Related Issue
#250 
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
Please resolve conflicts.`

**Comment by Utsavladia** [comment]
@Agarwalvidu resolved ✅

**Comment by Agarwalvidu** [comment]
Can you please add some screenshots to your work.

**Comment by Utsavladia** [comment]
@Agarwalvidu 
Sure I have not connect the backend but you can see the click to close function on no course found option too...
## Here is the demo video

https://github.com/user-attachments/assets/f5834b26-8694-462d-a52e-d1abeabeef6b

**Comment by Utsavladia** [comment]
@Agarwalvidu  
kindly review this PR its been 1 week i opened it

**Review by dhananjay6561 — COMMENTED** [review]
Your code is having conflicts with main branch.

**Comment by Utsavladia** [comment]
@dhananjay6561 okay I'll resolve it now

**Review by dhananjay6561 — COMMENTED** [review]
the code seems fine to me. however it still shows that it conflicts with main branch

**Comment by Utsavladia** [comment]
@Agarwalvidu 
Kindly merge this PR before closing of GSSOC 🙂

**Pull request merged**
