### PR TITLE
I did changes in contact section

### PR DESCRIPTION
**Pull request by SCR01**
## Related Issue
#264 

## Description
This PR addresses the grammatical error in our website's "Contact Us" section. The phrase "Chat on us" has been corrected to "Chat with us" to enhance clarity and professionalism.

## Type of PR

- [✔️] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots/videos (if applicable)

Before:

346315582-0d3f506c-6de8-4964-b375-ad5a4399ae0b

After:

Screenshot 2024-07-14 202628

Video:

https://github.com/user-attachments/assets/80371c02-6a33-4020-8aed-2e97e3170f29

## Checklist:
[✅ ] I have performed a self-review of my code
[✅ ] I have read and followed the Contribution Guidelines.
[✅ ] I thoroughly tested the changes before submitting this pull request.
[✅ ] After making the changes, I have provided relevant issue numbers, screenshots, and videos.
[✅ ] I have commented on my code, particularly in hard-to-understand areas.

Additional information

Benefits of the Correction:

- Enhances the professionalism of our website.
- Improves clarity and ensures users understand the contact options available to them.
- Helps in maintaining the overall quality and credibility of our communication.

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
I can't see any changes regarding this in files changed??

**Comment by SCR01** [comment]
@Agarwalvidu  I made the relevant changes.

**Comment by Agarwalvidu** [comment]
Your changes must be in just contact details and you have changed 5 other files too
Please look into this.

**Comment by Agarwalvidu** [comment]
@SCR01 
We can do one thing I am closing this PR, just sync your fork, and clone the repo again and then raise the PR after making your changes. I will merge it then.

**Comment by SCR01** [comment]
@Agarwalvidu  ok, thank you so much.

**Pull request closed without merging**
