### PR TITLE
Fix Navbar Sticky Behavior When Scrolling #12

### LINKED ISSUE #12: Navbar Not Sticky When Scrolling
As the user scrolls down the page, the navbar should remain fixed at the top of the viewport. 
ensuring easy access to navigation links.

@Muskansahuincredible  Please assign it to me. Also, please add Labels 

here is a screenshot of this issue
image

### PR DESCRIPTION
**Pull request by shivamgaur99**
Fixes #12 

Changes made:
- Implemented tailwind css to make the navbar sticky when scrolling
- updated .gitignore file

image

### CODE REVIEW

**Comment by shivamgaur99** [comment]
@Muskansahuincredible issue has been fixed please review

**Comment by shivamgaur99** [comment]
@techmannih please look this After merging some PR, the application is not starting now

**Comment by techmannih** [comment]
this is not working, raise another pr screenshot

**Comment by shivamgaur99** [comment]
@techmannih do I need to create a new pull request again? Because it has been merged

image

**Pull request merged**
