### PR TITLE
Added the "Contribute" link

### PR DESCRIPTION
**Pull request by ayush-848**
## Related Issue
#153 

## Description
Added the contribute link under the community headline
on clicking it, user gets directed to studynotion repo

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ayush-848** [comment]
@Muskansahuincredible please check my PR

**Comment by techmannih** [comment]
This branch is conflict. Solve and then commit.

**Comment by ayush-848** [comment]
> This branch is conflict. Solve and then commit.

@techmannih Done

**Comment by ayush-848** [comment]
@techmannih please check it

**Comment by techmannih** [comment]
This branch is conflict. Solve and then commit

**Comment by ayush-848** [comment]
@techmannih done, now check it

**Comment by ayush-848** [comment]
@techmannih check it I have already resolved the conflicts

**Pull request merged**
