### PR TITLE
Added Legal Pages: "Privacy Policy" and "Terms and Conditions"

### LINKED ISSUE #194: 💡Adding Legal Pages: "Privacy Policy", "Terms and Conditions" in Footer.
### Description

Hey @Muskansahuincredible and @techmannih I would like to add privacy policy and terms and conditions pages in footer section of study notion website

image

Could you please assign this issue to me under GSSOC24?

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines
- [X] I have read the Code Of Conduct
- [X] The changes don't break the code

### PR DESCRIPTION
**Pull request by MastanSayyad**
closes #194 

## Description

Hey @Muskansahuincredible and @techmannih  I have added Privacy Policy and Terms and Conditions Pages in footer section pls take a look and review it thank you!

## Type of PR

- [x] Feature enhancement

### Footer

image

### Privacy Policy
image

### Terms and Conditions
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
please add labels @techmannih

**Comment by MastanSayyad** [comment]
@techmannih and @Muskansahuincredible please Add the Labels to this merge PR so that it can get counted under GSSOC 24.

**Comment by MastanSayyad** [comment]
Please add the labels @techmannih , @Muskansahuincredible

**Comment by MastanSayyad** [comment]
@Muskansahuincredible

**Comment by MastanSayyad** [comment]
@Muskansahuincredible and @techmannih Its been more than 2 weeks Please add the gssoc and level 2 labels, I don't know what stopping you to do that as I can see you are active and merging labeling to only a single contributor, it is important for me to score in leaderboard, this is my last request to you otherwise I have to report this to the GSSOC maintainers. Hope you understand, Thank You!

**Comment by MastanSayyad** [comment]
@sanjay-kv Sir, sorry for the interruption please add the labels for it as it's about been a month but still the PAs didn't add the labels for this merged PR

**Comment by sanjay-kv** [comment]
@MastanSayyad Keep a note of this PR, at the end of the program we will add relevant score to it. i can see the chain above and noreply actions. Even I don't have access to this repo.

**Pull request merged**
